In [4]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

# German Credit Data, UCI dataset ID 144
german_credit = fetch_ucirepo(id=144)

X = german_credit.data.features
y = german_credit.data.targets

print(X.shape)
print(y.shape)
X.head()

(1000, 20)
(1000, 1)

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,4,A121,67,A143,A152,2,A173,1,A192,A201
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,2,A121,22,A143,A152,1,A173,1,A191,A201
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,3,A121,49,A143,A152,1,A172,2,A191,A201
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,4,A122,45,A143,A153,1,A173,2,A191,A201
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,4,A124,53,A143,A153,2,A173,2,A191,A201

In [5]:
column_names = {
    "Attribute1": "checking_account_status",
    "Attribute2": "duration_months",
    "Attribute3": "credit_history",
    "Attribute4": "purpose",
    "Attribute5": "credit_amount",
    "Attribute6": "savings_account",
    "Attribute7": "employment_years",
    "Attribute8": "installment_rate_pct",
    "Attribute9": "personal_status_sex",
    "Attribute10": "other_debtors",
    "Attribute11": "residence_since_years",
    "Attribute12": "property",
    "Attribute13": "age",
    "Attribute14": "other_installment_plans",
    "Attribute15": "housing",
    "Attribute16": "num_existing_credits",
    "Attribute17": "job",
    "Attribute18": "num_dependents",
    "Attribute19": "telephone",
    "Attribute20": "foreign_worker",
}

X = X.rename(columns=column_names)
X.head()

,checking_account_status,duration_months,credit_history,purpose,credit_amount,savings_account,employment_years,installment_rate_pct,personal_status_sex,other_debtors,residence_since_years,property,age,other_installment_plans,housing,num_existing_credits,job,num_dependents,telephone,foreign_worker
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,4,A121,67,A143,A152,2,A173,1,A192,A201
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,2,A121,22,A143,A152,1,A173,1,A191,A201
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,3,A121,49,A143,A152,1,A172,2,A191,A201
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,4,A122,45,A143,A153,1,A173,2,A191,A201
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,4,A124,53,A143,A153,2,A173,2,A191,A201

In [ ]:

X.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   checking_account_status  1000 non-null   str
 1   duration_months          1000 non-null   int64
 2   credit_history           1000 non-null   str
 3   purpose                  1000 non-null   str
 4   credit_amount            1000 non-null   int64
 5   savings_account          1000 non-null   str
 6   employment_years         1000 non-null   str
 7   installment_rate_pct     1000 non-null   int64
 8   personal_status_sex      1000 non-null   str
 9   other_debtors            1000 non-null   str
 10  residence_since_years    1000 non-null   int64
 11  property                 1000 non-null   str
 12  age                      1000 non-null   int64
 13  other_installment_plans  1000 non-null   str
 14  housing                  1000 non-null   str
 15  num_existing_credits     1000 non-null   int64
 16  job                      1000 non-null   str
 17  num_dependents           1000 non-null   int64
 18  telephone                1000 non-null   str
 19  foreign_worker           1000 non-null   str
dtypes: int64(7), str(13)
memory usage: 156.4 KB

In [6]:
y.value_counts()

class
1        700
2        300
Name: count, dtype: int64

In [7]:
import pandas as pd

# Turn text categories (A11, A34...) into numeric columns the model can use
X_encoded = pd.get_dummies(X, drop_first=True)

# Target: UCI encodes 1 = good, 2 = bad. Convert to 0/1 (1 = bad risk, standard convention)
y_binary = (y["class"] == 2).astype(int)

print(X_encoded.shape)
X_encoded.head()

(1000, 48)

,duration_months,credit_amount,installment_rate_pct,residence_since_years,age,num_existing_credits,num_dependents,checking_account_status_A12,checking_account_status_A13,checking_account_status_A14,...,property_A124,other_installment_plans_A142,other_installment_plans_A143,housing_A152,housing_A153,job_A172,job_A173,job_A174,telephone_A192,foreign_worker_A202
0,6,1169,4,4,67,2,1,False,False,False,...,False,False,True,True,False,False,True,False,True,False
1,48,5951,2,2,22,1,1,True,False,False,...,False,False,True,True,False,False,True,False,False,False
2,12,2096,2,3,49,1,2,False,False,True,...,False,False,True,True,False,True,False,False,False,False
3,42,7882,2,4,45,1,2,False,False,False,...,False,False,True,False,True,False,True,False,False,False
4,24,4870,3,4,53,2,2,False,False,False,...,True,False,True,False,True,False,True,False,False,False

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_binary, test_size=0.2, random_state=42, stratify=y_binary
)

print(X_train.shape, X_test.shape)

(800, 48) (200, 48)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.78
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       140
           1       0.67      0.52      0.58        60

    accuracy                           0.78       200
   macro avg       0.74      0.70      0.72       200
weighted avg       0.77      0.78      0.77       200

c:\Users\priya\Desktop\german-credit-risk\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, classification_report

model = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000)
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.785
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       140
           1       0.66      0.58      0.62        60

    accuracy                           0.79       200
   macro avg       0.75      0.73      0.73       200
weighted avg       0.78      0.79      0.78       200